### ISSUE TITLE
--picture with package

### ISSUE THREAD

**Issue by gahel** [freegeek-pdx/mkuser#1]
Great tool! Testing it out I am struggling with specifying a image file for inclusion in a pkg. It works if creating the user directly without creating pkg, and the pkg works if I leave out the --picture

./mkuser.sh -n "testadmin" -f "testadmin" -u "407" -a --password-prompt --dont-create-home --picture "/tmp/logo.png" --package-version "1.0" --package-identifier no.example.testadmin --package-path

Error from installer-pkg:
ERROR 2: Invalid option "/private/tmp/no.example.testadmin+1641307482-551296118/mkuser.picture".
ERROR 2: Invalid duplicate "--stdin-password" option.
WARNING: User WILL NOT be created since INVALID OPTIONS OR PARAMETERS were specified, but still running checks to detect more possible errors.
ERROR 37: NOT creating Admin User "testadmin" since INVALID OPTIONS OR PARAMETERS were specified.

View "Show All Logs" output of the "Installer Log" (within the "Window" menu) for more details. Or, you can view "install.log" within the "Console" app.

Log:
Jan  4 16:58:49 MacBook-Pro Installer[10221]: Failed to load specified background image
Jan  4 16:58:49 MacBook-Pro Installer[10221]: Could not load resource readme: (null)
Jan  4 16:58:49 MacBook-Pro Installer[10221]: Could not load resource license: (null)

**Comment by PicoMitchell** [comment]
I'm so sorry for the issue!

I noticed this issue as well shortly after releasing the last update (an unfortunate small mistake leftover from when I changed long form options to needing double hyphens, which I allowed to work with with single hyphen earlier in development) and have a fix coming out later today along with some other small nice changes.

**Comment by PicoMitchell** [comment]
If you're comfortable working in the source code, you can fix this issue very easily before the next update with the fix is available later today.

On line 3016, you just need to change `-picture` to `--picture` and then create a new package with the updated script: https://github.com/freegeek-pdx/mkuser/blob/490d6a62c0fb01a29c3537a238db9eb24599a7f1/mkuser.sh#L3016

**Comment by gahel** [comment]
Awsome - that fixed it! Thanks

**Comment by PicoMitchell** [comment]
This bug has been fixed in version 2022.1.4-1 which can now be downloaded on the releases page: https://github.com/freegeek-pdx/mkuser/releases
