### ISSUE TITLE
Possible FR: kill loginwindow sessions when using --skip-setup-assistant and setup assistant is running

### ISSUE THREAD

**Issue by mikedowler** [freegeek-pdx/mkuser#3]
I'm not sure that this counts as a bug, since I think behaviour is line with what is documented in the wiki.

However, if I use `mkuser` to create a package for installation at MDM enrollment (I'm using Jamf), then I am forced to "Create a Computer Account" in the setup assistant in order to progress.  This somewhat negates the purpose of using `mkuser` - especially given the utility of the modern MDM erase command, which makes it less worthwhile to use something like MDS/Imagr (where the package could be installed during OS installation, instead of at first boot setup).

I'd like to suggest that, where the `--skip-setup-assistant` flag is being used (at least with the `firstBootOnly` option), a check be added to see if the currently-logged-in user is `_mbtsetupuser`, and if so, the `killall loginwindow` command is run.  This will kill the Setup Assistant session and return to the login screen to log in with the user created by `mkuser`

**Comment by PicoMitchell** [comment]
Thanks for this feedback! I hadn't encountered this possible timing issue myself as my main testing with `mkuser` packages at boot are with MDS which will either happen during the macOS installation process or Setup Assistant would be bypassed by other MDS code.

But, it does sound reasonable for an `mkuser` process to be able to exit Setup Assistant when `--skip-setup-assistant` is specified and the system is currently sitting at Setup Assistant.

This would be one of those features were the code is very easy, but testing it across macOS 10.13 through 12 may take me a little while, so I can't say exactly when I'll have an update out with this change. But, if you wanted to experiment with it yourself I think it would be pretty easy to add some code right before the final success message to create a new condition that checks if `$skip_setup_assistant_on_first_boot` is true and Setup Assistant is currently running to then exit Setup Assistant based on the behavior you describe.

**Comment by PicoMitchell** [comment]
I've just released `mkuser` version 2022.6.1-1 which will now exit Setup Assistant (or Language Chooser) if still running when a user is created that is set to skip first boot Setup Assistant.

https://github.com/freegeek-pdx/mkuser/releases
