### ISSUE TITLE
auto-login appears to be broken on Ventura

### ISSUE THREAD

**Issue by grahamc** [freegeek-pdx/mkuser#5]
I run mkuser.sh with MDM on first provision. I execute it like this:

```
openssl rand -base64 48 |./mkuser.sh --do-not-confirm --administrator --automatic-login --no-picture --stdin-password --account-name ci --full-name ci
```

My full script I push out via mdm looks like this: https://github.com/DeterminateSystems/macos-ephemeral/blob/247c80124bc072d90adce90f908f79b9ed571c96/auto-login.sh

on Ventura, this appears to be failing:

```
mkuser: Validating specified options and parameters (version 2022.8.3-1 on macOS 13.0 22A5331f)...
mkuser: Checking that specified parameters don't conflict with existing users...
mkuser: Creating Admin Auto-Login User "ci" with User ID 502...
mkuser: Verifying "ci" user creation...
mkuser: Setting password for "ci" user...
mkuser: Creating home folder for "ci" user...
creating home directories for (mac-ephemeral-xxx.local)
created (/Users/ci)
mkuser: Sharing "ci" user Public folder...
mkuser: Making "ci" user an administrator...
mkuser: Setting "ci" user to automatically login...
2022-08-27 11:42:57.595 sysadminctl[1288:10610] SACSetAutoLoginPassword error:22
2022-08-27 11:42:57.628 sysadminctl[1291:10624] Automatic login is OFF.
mkuser ERROR 54-6038: Created user "ci", but failed to setup auto-login using the "sysadminctl -autologin set" command.
```

This isn't a problem for me, I will roll back to stable, but thought I'd try to help give some advance notice.

**Comment by PicoMitchell** [comment]
Thanks for reporting this issue. I've run into this myself and have a workaround to fallback to the previous manual auto-login setting code instead of using the new Ventura technique, but I haven't released it yet since I've been busy with other work. I can try to release that update next week though.

Ultimately this is a bug in the new `sysadminctl -autologin set` command though, and I would recommend reporting Feedback to Apple (as I have) that it fails consistently with that error 22 when it's run via LaunchDaemon or when run when a user is not currently logged in.

**Comment by PicoMitchell** [comment]
Actually, was this failing for you when run via Terminal when a user is logged in? If so, I haven't seen it fail in that scenario. Regardless, I would recommend filing Feedback so Apple can make this new `sysadminctl -autologin set` command work properly.

**Comment by grahamc** [comment]
Holy cow I didn't expect a reply on a Saturday. Thanks! I'll report it upstream and refer to this ticket. Thanks!

**Comment by PicoMitchell** [comment]
Thanks for filing Feedback with Apple!

I'll post to and close this issue when I update `mkuser` with the fallback when `sysadminctl -autologin set` fails.

**Comment by PicoMitchell** [comment]
This issue is now worked around in `mkuser` 2022.9.2-1 by falling back to the previous manual auto-login code if the new `sysadminctl -autologin set` fails.

https://github.com/freegeek-pdx/mkuser/releases
